### ISSUE TITLE
Consider adding Graph Convolutional Policy Network to the models

### ISSUE THREAD

**Issue by hbq1** [molecularsets/moses#15]
Seems like recently proposed in [You et al. 2018](https://papers.nips.cc/paper/7877-graph-convolutional-policy-network-for-goal-directed-molecular-graph-generation) GCPN significantly outperforms existing baselines. It could be a good idea to add the model to MOSES.

**Comment by lilleswing** [comment]
The metrics from the graph based approaches (Also MolDQN) don't really apply.  Many of the metrics presented here are about diversity which is an non-optimized parameter.

The same metrics don't really make sense for the de-novo techniques which play the game of editing a single molecule instead of generating a molecule whole cloth.
