### ISSUE TITLE
Insights on VAE's KL annealing scheme

### ISSUE THREAD

**Issue by maxime1310** [molecularsets/moses#42]
Hello, 

In most implementations of VAE for molecular generation on the web there seems to be a trend to downweight the KL penalty/suppress the reparametrization in the VAE training, basically degenerating the model into a standard AE. The reason being that a vanilla VAE seems to be unable to learn from a SMILES dataset otherwise. 

In Moses VAE's training scheme it seems to me that the KL penalty has a weighting factor that starts at 0 and grows linearly towards 1 with the number of epochs increasing. 

Do you find that this annealing of the KL term allows to get the best of both worlds, i.e not train just a plain AE while still being able to acheive low reconstruction error and high log-likelihood?
Any insights on the impact of this scheme and of the KL penalty in general on the training of a VAE on a SMILES dataset?

Thanks for your amazing repo!

**Comment by beangoben** [comment]
In my experience working on the VAE, the KL annealer helps to train the model.
To be more specific, when training your encoder and decoders right off the bat variationally (KL-term constant) can lead to a lot of instability while training. So a good first step is to train them as a AE and at some moment slowly switch on the KL term.  It allows the model to arrive to a 'decent' spot (trained as AE) before going VAE. A similar pattern lies with ORGAN, you need to train pre-train your generators so that they are in a decent spot before competing with the discriminator. There are many ways of doing this, most are just engineering, hence MOSES's approach also works. 

For the original VAE i think around epoch 30 we start the KL annealing.

**Comment by maxime1310** [comment]
Thanks for the answer! Indeed with a simple linear annealing scheme for the KL I'm able to get very decent results.

**Comment by eminemichael** [comment]
> For the original VAE i think around epoch 30 we start the KL annealing.

Sorry, does it mean that letting weight factor of KL penalty increase to 1 at 30th epoch linearly?
