### ISSUE TITLE
Posterior collapse for the VAE

### ISSUE THREAD

**Issue by maxime1310** [molecularsets/moses#45]
Hi everyone,

After training the VAE for 50 epochs, when sampling from the prior I get a quite nice distribution of molecules and similar metrics as reported in the paper/the readme.
On the other hand, the reconstruction loss is quite high (approx. 0.5) while the KL loss is approx. zero, and the VAE fails to reconstruct accurately molecules.
This looks like posterior collapse to me (indeed, all smiles are encoded into roughly the same mean/variances), and while this still yields a nice generator, it removes the main interest of the VAE (obtaining a meaningful latent space) in contrast to a plain charRNN for instance.
Any thoughts/advices/comments on the matter?

Thanks

**Comment by danpol** [comment]
Hi, @maxime1310!

Yes, indeed the model converges to charRNN-like weights and gets better metrics for collapsed priors. It is expected behavior since we don't need the latent codes for the generation. One can think of VAE here as a CharRNN with an auxiliary reconstruction regularizer as opposed to a standard view (reconstruction with auxiliary KL regulariazer)
